// packages/editor/src/components/jumbotron.component.tsx
import {
  ComponentData,
  ComponentInstance,
  ContentType,
  defineComponent,
  onDestroy,
  Slot, useContext,
  useSlots,
  useState,
  VElement
} from '@textbus/core'
import { ComponentLoader, SlotParser } from '@textbus/browser'
import { Injector } from '@tanbo/di'
import { headingComponent } from './heading.component'
import { paragraphComponent } from './paragraph.component'
import { Dialog } from '../dialog'
import { Form } from '../uikit/forms/form'
import { I18n } from '../i18n'
import { FormTextField } from '../uikit/forms/form-text-field'
import { FileUploader } from '../file-uploader'

export interface JumbotronComponentState {
  minHeight: string
  backgroundImage: string
  backgroundSize: string
  backgroundPosition: string
}

export function createJumbotronSlot(injector: Injector) {
  const slot = new Slot([
    ContentType.Text,
    ContentType.InlineComponent,
    ContentType.BlockComponent
  ])
  const h1 = headingComponent.createInstance(injector)
  h1.slots.first!.insert('Hello, world!')
  const p1 = paragraphComponent.createInstance(injector)
  p1.slots.first!.insert('你好，我是 TextBus 富文本编辑器。')
  const p2 = paragraphComponent.createInstance(injector)
  p2.slots.first!.insert('你现在还好吗？')

  slot.insert(h1)
  slot.insert(p1)
  slot.insert(p2)
  return slot
}

export const jumbotronComponent = defineComponent({
  type: ContentType.BlockComponent,
  name: 'JumbotronComponent',
  setup(initData?: ComponentData<JumbotronComponentState>) {
    const slots = useSlots(initData?.slots || [])
    const injector = useContext()
    const dialog = injector.get(Dialog)
    const i18n = injector.get(I18n)
    const fileUploader = injector.get(FileUploader)
    if (slots.length === 0) {
      slots.push(createJumbotronSlot(injector))
    }
    let state = initData?.state || {
      minHeight: '200px',
      backgroundImage: '',
      backgroundPosition: 'center',
      backgroundSize: 'cover'
    }
    const stateController = useState(state)
    const sub = stateController.onChange.subscribe(newState => {
      state = newState
    })
    onDestroy(() => {
      sub.unsubscribe()
    })
    const componentI18n = i18n.getContext('components.jumbotronComponent')
    const childI18n = componentI18n.getContext('setting.form')

    function setting() {
      const form = new Form({
        title: childI18n.get('title'),
        confirmBtnText: childI18n.get('confirmBtnText'),
        cancelBtnText: childI18n.get('cancelBtnText'),
        items: [
          new FormTextField({
            name: 'minHeight',
            value: '200px',
            placeholder: childI18n.get('minHeightInputPlaceholder'),
            label: childI18n.get('minHeightLabel')
          }),
          new FormTextField({
            label: childI18n.get('backgroundImageLabel'),
            name: 'backgroundImage',
            value: state.backgroundImage,
            placeholder: childI18n.get('backgroundImageInputPlaceholder'),
            canUpload: true,
            uploadType: 'image',
            fileUploader,
            uploadBtnText: childI18n.get('uploadBtnText'),
            validateFn(value: string): string | false {
              if (!value) {
                return childI18n.get('validateErrorMessage')
              }
              return false
            }
          })
        ]
      })
      dialog.show(form.elementRef)
      const sub1 = form.onComplete.subscribe(data => {
        stateController.update(draft => {
          Object.assign(draft, data)
        })
        dialog.hide()
        sub1.unsubscribe()
        sub2.unsubscribe()
      })
      const sub2 = form.onCancel.subscribe(() => {
        dialog.hide()
        sub1.unsubscribe()
        sub2.unsubscribe()
      })
    }

    return {
      render(isOutputMode: boolean, slotRender): VElement {
        return (
          <tb-jumbotron style={{
            backgroundImage: `url("${state.backgroundImage}")`,
            backgroundSize: state.backgroundSize || 'cover',
            backgroundPosition: state.backgroundPosition || 'center',
            minHeight: state.minHeight
          }}>
            {
              !isOutputMode &&
              <button type="button" class="tb-jumbotron-setting" onClick={setting}>{componentI18n.get('settingBtn')}</button>
            }
            {
              slotRender(slots.get(0)!, () => {
                return <div/>
              })
            }
          </tb-jumbotron>
        )
      }
    }
  }
})

export const jumbotronComponentLoader: ComponentLoader = {
  component: jumbotronComponent,
  resources: {
    styles: [
      `
tb-jumbotron {
  display: block;
  min-height: 200px;
  margin-bottom: 1em;
  background-color: #eee;
  padding: 20px;
  position: relative;
  border-radius: 4px;
  overflow: hidden;
}
`
    ],
    editModeStyles: [
      // eslint-disable-next-line max-len
      '.tb-jumbotron-setting { display:none; border-radius: 4px; font-size: 14px;position: absolute; right: 10px; top: 10px; background: #fff; box-shadow: 1px 2px 3px rgba(0,0,0,.1); color: #333; border: 0; outline: none; cursor: pointer;}.tb-jumbotron-setting:hover{color: #1296db} tb-jumbotron:hover .tb-jumbotron-setting{display:block} '
    ]
  },
  match(element: HTMLElement): boolean {
    return element.nodeName.toLowerCase() === 'tb-jumbotron'
  },
  read(element: HTMLElement, context: Injector, slotParser: SlotParser): ComponentInstance {
    const style = element.style
    return jumbotronComponent.createInstance(context, {
      state: {
        backgroundImage: (style.backgroundImage || '').replace(/^url\(['"]?|['"]?\)$/g, ''),
        backgroundSize: style.backgroundSize,
        backgroundPosition: style.backgroundPosition,
        minHeight: style.minHeight
      },
      slots: [
        slotParser(new Slot([
          ContentType.BlockComponent,
          ContentType.InlineComponent,
          ContentType.Text
        ]), element.children[0] as HTMLElement || document.createElement('div'))
      ]
    })
  }
}

// src/lib/components/extensions/jumbotron.component.tsx
import { Injectable } from '@tanbo/di';

import {
  Component,
  ComponentLoader, ComponentSetter, ComponentControlPanelView,
  DivisionAbstractComponent,
  SlotRenderFn,
  VElement,
  ViewData, SingleSlotRenderFn
} from '../../core/_api';
import { ComponentCreator, UIDialog } from '../../ui/_api';
import { BlockComponent } from '../_api';
import { FileUploader, Form, FormTextField } from '../../ui/_api';
import { I18n } from '../../i18n';

export interface JumbotronOptions {
  minHeight: string;
  backgroundImage: string;
  backgroundSize: string;
  backgroundPosition: string;
}

@Injectable()
class JumbotronComponentSetter implements ComponentSetter<JumbotronComponent> {
  constructor(private uploader: FileUploader,
              private i18n: I18n) {
  }

  create(instance: JumbotronComponent): ComponentControlPanelView {
    const childI18n = this.i18n.getContext('components.jumbotronComponent.setter');
    const form = new Form({
      mini: true,
      confirmBtnText: childI18n.get('confirmBtnText'),
      items: [
        new FormTextField({
          name: 'minHeight',
          value: instance.options.minHeight,
          placeholder: childI18n.get('minHeightInputPlaceholder'),
          label: childI18n.get('minHeightLabel')
        }),
        new FormTextField({
          label: childI18n.get('backgroundImageLabel'),
          name: 'backgroundImage',
          placeholder: childI18n.get('backgroundImageInputPlaceholder'),
          canUpload: true,
          uploadType: 'image',
          uploadBtnText: childI18n.get('uploadBtnText'),
          value: instance.options.backgroundImage,
          validateFn(value: string): string | null {
            if (!value) {
              return childI18n.get('validateErrorMessage');
            }
            return null;
          }
        })
      ]
    })

    form.setFileUploader(this.uploader);

    form.onComplete.subscribe(map => {
      instance.options.minHeight = map.get('minHeight');
      instance.options.backgroundImage = map.get('backgroundImage');
      instance.slot.markAsDirtied();
    });
    return {
      title: childI18n.get('title'),
      view: form.elementRef
    }
  }
}

class JumbotronComponentLoader implements ComponentLoader {
  match(element: HTMLElement): boolean {
    return element.nodeName.toLowerCase() === 'tb-jumbotron';
  }

  read(element: HTMLElement): ViewData {
    const style = element.style;
    const component = new JumbotronComponent({
      backgroundImage: (style.backgroundImage || '').replace(/^url\(['"]?|['"]?\)$/g, ''),
      backgroundSize: style.backgroundSize,
      backgroundPosition: style.backgroundPosition,
      minHeight: style.minHeight
    });
    return {
      component: component,
      slotsMap: [{
        from: element,
        toSlot: component.slot
      }]
    };
  }
}

@Component({
  loader: new JumbotronComponentLoader(),
  providers: [{
    provide: ComponentSetter,
    useClass: JumbotronComponentSetter
  }],
  styles: [
    `
tb-jumbotron {
  display: block;
  min-height: 200px;
  margin-bottom: 1em;
  background-color: #eee;
  padding: 20px;
}
`
  ]
})
export class JumbotronComponent extends DivisionAbstractComponent {
  constructor(public options: JumbotronOptions) {
    super('tb-jumbotron');
  }

  clone(): JumbotronComponent {
    const component = new JumbotronComponent({
      ...this.options
    });
    component.slot.from(this.slot.clone());
    return component;
  }

  slotRender(isOutputMode: boolean, slotRendererFn: SingleSlotRenderFn): VElement {
    const vEle = <tb-jumbotron style={{
      backgroundImage: `url("${this.options.backgroundImage}")`,
      backgroundSize: this.options.backgroundSize || 'cover',
      backgroundPosition: this.options.backgroundPosition || 'center',
      minHeight: this.options.minHeight
    }}/>;
    return slotRendererFn(this.slot, vEle);
  }

  render(isOutputMode: boolean, slotRendererFn: SlotRenderFn): VElement {
    return slotRendererFn(this.slot)
  }
}

export const jumbotronComponentExample: ComponentCreator = {
  name: i18n => i18n.get('components.jumbotronComponent.creator.name'),
  category: 'TextBus',
  example: `<img src="data:image/svg+xml;charset=UTF-8,${encodeURIComponent('<svg width="100" height="70" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><defs><linearGradient id="bg" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stop-color="#6ad1ec"/><stop offset="100%" stop-color="#fff"/></linearGradient></defs><g><rect fill="url(#bg)" height="100%" width="100%"/></g><path fill="#fff" opacity="0.3" d="M81.25 28.125c0 5.178-4.197 9.375-9.375 9.375s-9.375-4.197-9.375-9.375 4.197-9.375 9.375-9.375 9.375 4.197 9.375 9.375z"></path><path fill="#fff" opacity="0.3"  d="M87.5 81.25h-75v-12.5l21.875-37.5 25 31.25h6.25l21.875-18.75z"></path><text font-family="Helvetica, Arial, sans-serif" font-size="12" x="10" y="25" stroke-width="0.3" stroke="#000" fill="#000000">Hello, world!</text><text font-family="Helvetica, Arial, sans-serif" font-size="6" x="10" y="40" stroke-width="0" stroke="#000" fill="#000000">我是 TextBus 富文本编辑器。</text><text font-family="Helvetica, Arial, sans-serif" font-size="6" x="10" y="50" stroke-width="0" stroke="#000" fill="#000000">别来无恙？</text></svg>')}">`,
  factory(dialog: UIDialog, fileUploader: FileUploader, i18n) {
    const childI18n = i18n.getContext('components.jumbotronComponent.creator.form');

    const form = new Form({
      title: childI18n.get('title'),
      confirmBtnText: childI18n.get('confirmBtnText'),
      cancelBtnText: childI18n.get('cancelBtnText'),
      items: [
        new FormTextField({
          name: 'minHeight',
          value: '200px',
          placeholder: childI18n.get('minHeightInputPlaceholder'),
          label: childI18n.get('minHeightLabel')
        }),
        new FormTextField({
          label: childI18n.get('backgroundImageLabel'),
          name: 'backgroundImage',
          placeholder: childI18n.get('backgroundImageInputPlaceholder'),
          canUpload: true,
          uploadType: 'image',
          uploadBtnText: childI18n.get('uploadBtnText'),
          validateFn(value: string): string | null {
            if (!value) {
              return childI18n.get('validateErrorMessage');
            }
            return null;
          }
        })]
    })

    form.setFileUploader(fileUploader);
    return new Promise<JumbotronComponent>((resolve) => {
      dialog.dialog(form.elementRef);
      const s = form.onComplete.subscribe(data => {
        const component = new JumbotronComponent({
          backgroundPosition: 'center center',
          backgroundSize: 'cover',
          backgroundImage: data.get('backgroundImage'),
          minHeight: data.get('minHeight') + ''
        });
        const h1 = new BlockComponent('h1');
        h1.slot.append('Hello, world!')
        const p1 = new BlockComponent('p')
        p1.slot.append('你好，我是 TextBus 富文本编辑器。');
        const p2 = new BlockComponent('p');
        p2.slot.append('你现在还好吗？');

        component.slot.append(h1);
        component.slot.append(p1);
        component.slot.append(p2);

        s.unsubscribe();
        resolve(component)
        dialog.close();
      });
      const b = form.onClose.subscribe(() => {
        s.unsubscribe();
        b.unsubscribe();
        dialog.close();
      })
    })
  }
}
