// src/lib/additional-components/word-explain.component.tsx
import {
  BackboneAbstractComponent, Component,
  ComponentLoader,
  FormatAbstractData,
  FormatEffect,
  Fragment, SingleSlotRenderFn, SlotRendererFn,
  VElement,
  ViewData
} from '../core/_api';
import { BrComponent } from '../components/br.component';
import { ComponentCreator } from '../workbench/component-stage';
import { textAlignFormatter } from '../formatter/block-style.formatter';

export interface WordExplainParams {
  title: Fragment;
  subtitle: Fragment;
  detail: Fragment;
}

class WordExplainComponentLoader implements ComponentLoader {
  match(element: Element): boolean {
    return element.nodeName.toLowerCase() === 'tb-word-explain';
  }

  read(element: Element): ViewData {
    const title = element.querySelector('.tb-word-explain-title');
    const subtitle = element.querySelector('.tb-word-explain-subtitle');
    const detail = element.querySelector('.tb-word-explain-detail');

    const titleFragment = new Fragment();
    const subtitleFragment = new Fragment();
    const detailFragment = new Fragment();

    const component = new WordExplainComponent({
      title: titleFragment,
      subtitle: subtitleFragment,
      detail: detailFragment
    });
    return {
      component,
      slotsMap: [{
        from: title as HTMLElement,
        toSlot: titleFragment
      }, {
        from: subtitle as HTMLElement,
        toSlot: subtitleFragment
      }, {
        from: detail as HTMLElement,
        toSlot: detailFragment
      }]
    };
  }
}

@Component({
  loader: new WordExplainComponentLoader(),
  styles: [
    `
tb-word-explain {
  display: flex;
  margin-top: 1em;
  margin-bottom: 1em;
  padding: 10px 20px;
  background-color: #f8f8f9;
  border-radius: 10px;
}

.tb-word-explain-title-group {
  width: 140px;
  padding-right: 20px;
}
.tb-word-explain-title {
  margin:0;
  font-size: inherit;
}
.tb-word-explain-subtitle {
  margin: 0;
  font-weight: 300;
  font-size: 0.9em;
}
.tb-word-explain-detail {
  flex: 1;
  padding-left: 20px;
  border-left: 1px dashed #ddd;
}
@media screen and (max-width: 767px) {
  tb-word-explain {
    display: block;
  }
  .tb-word-explain-title-group {
    width: auto;
    padding-right: 0;
    display: flex;
    align-items: baseline;
    padding-bottom: 0.5em;
    margin-bottom: 0.5em;
    border-bottom: 1px dashed #ddd;
  }
  .tb-word-explain-subtitle {
    margin-left: 0.5em;
    font-weight: 300;
    font-size: 0.9em;
  }
  .tb-word-explain-detail {
    padding-left: 0;
    border-left: none;
  }
}
`
  ],
  editModeStyles: [
    `
tb-word-explain {
  position: relative;
}
tb-word-explain:hover .tb-word-explain-close {
  display: block;
}
.tb-word-explain-close {
  display: none;
  position: absolute;
  right: 10px;
  top: 0;
  font-size: 20px;
  line-height: 1;
  cursor: pointer;
}
.tb-word-explain-close:hover {
  transform: scale(1.2);
}
.tb-word-explain-close:before {
  content: "\u00d7";
}
`
  ]
})
export class WordExplainComponent extends BackboneAbstractComponent {
  private readonly title: Fragment;
  private readonly subtitle: Fragment;
  private readonly detail: Fragment;

  constructor(private params: WordExplainParams) {
    super('tb-word-explain');

    this.title = params.title;
    this.subtitle = params.subtitle;
    this.detail = params.detail;

    this.clean();
    this.push(this.title, this.subtitle, this.detail);
  }

  canDelete(): boolean {
    return false;
  }

  clone(): WordExplainComponent {
    return new WordExplainComponent({
      title: this.params.title.clone(),
      subtitle: this.params.subtitle.clone(),
      detail: this.params.detail.clone()
    });
  }

  slotRender(slot: Fragment, isOutputMode: boolean, slotRendererFn: SingleSlotRenderFn): VElement {
    switch (slot) {
      case this.title:
        return slotRendererFn(slot, <h3 className="tb-word-explain-title"/>);
      case this.subtitle:
        return slotRendererFn(slot, <div className="tb-word-explain-subtitle"/>);
      case this.detail:
        return slotRendererFn(slot, <div className="tb-word-explain-detail"/>);
    }
  }

  render(isOutputMode: boolean, slotRenderFn: SlotRendererFn): VElement {
    const title = this.slotRender(this.title, isOutputMode, (slot, contentContainer) => contentContainer)
    const subtitle = this.slotRender(this.subtitle, isOutputMode, (slot, contentContainer) => contentContainer);
    const detail = this.slotRender(this.detail, isOutputMode, (slot, contentContainer) => contentContainer);

    return (
      <tb-word-explain>
        <div className="tb-word-explain-title-group">
          {slotRenderFn(this.title, title, title)}
          {slotRenderFn(this.subtitle, subtitle, subtitle)}
        </div>
        {slotRenderFn(this.detail, detail, detail)}
        {
          !isOutputMode && <span className="tb-word-explain-close" onClick={() => {
            const parentFragment = this.parentFragment;
            parentFragment.remove(parentFragment.indexOf(this), 1);
          }
          }/>
        }
      </tb-word-explain>
    );
  }
}

export const wordExplainComponentExample: ComponentCreator = {
  name: '名词释义',
  category: 'TextBus',
  example: `<img alt="示例" src="data:image/svg+xml;charset=UTF-8,${encodeURIComponent('<svg width="100" height="70" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g><rect fill="#fff" height="100%" width="100%"/></g><defs><g id="item"><rect fill="#eee" height="18" width="90" rx="2" x="5" y="6"/><line x1="26" y1="9" x2="26" y2="20.5" stroke="#000" stroke-dasharray="0.8 0.8" stroke-width="0.1"></line><text font-family="Helvetica, Arial, sans-serif" font-size="6" x="10" y="14" stroke-width="0" stroke="#000" fill="#000000">名词</text><text font-family="Helvetica, Arial, sans-serif" font-size="5" x="12" y="20" stroke-width="0" stroke="#000" fill="#000000">说明</text><text font-family="Helvetica, Arial, sans-serif" font-size="6" x="30" y="14" stroke-width="0" stroke="#000" fill="#000000">详细解释...</text></g></defs><use xlink:href="#item"></use><use xlink:href="#item" transform="translate(0, 20)"></use><use xlink:href="#item" transform="translate(0, 40)"></use></svg>')}">`,
  factory() {
    const title = new Fragment();
    title.append('名词');
    title.apply(textAlignFormatter, {
      state: FormatEffect.Valid,
      abstractData: new FormatAbstractData({
        styles: {
          textAlign: 'right'
        }
      })
    })

    const subtitle = new Fragment();
    subtitle.append('说明');
    subtitle.apply(textAlignFormatter, {
      state: FormatEffect.Valid,
      abstractData: new FormatAbstractData({
        styles: {
          textAlign: 'right'
        }
      })
    })

    const detail = new Fragment();
    detail.append('详细解释');

    return new WordExplainComponent({
      title,
      subtitle,
      detail
    });
  }
}

// packages/editor/src/components/word-explain.component.tsx
import {
  Commander,
  ComponentData, ComponentInstance,
  ContentType,
  defineComponent, onContextMenu,
  onDestroy,
  onSlotRemove,
  Slot,
  SlotRender,
  useContext,
  useSelf,
  useSlots,
  useState,
  VElement
} from '@textbus/core'
import { ComponentLoader, SlotParser } from '@textbus/browser'
import { Injector } from '@tanbo/di'
import { I18n } from '../i18n'
import { Form, FormTextField } from '../uikit/forms/_api'
import { Dialog } from '../dialog'

export interface WordExplainComponentState {
  width: string
}

export const wordExplainComponent = defineComponent({
  type: ContentType.BlockComponent,
  name: 'WordExplainComponent',
  separable: false,
  setup(initData?: ComponentData<WordExplainComponentState>) {
    const slots = useSlots(initData?.slots || [])
    let state = initData?.state || {
      width: '140px'
    }

    while (slots.length < 3) {
      slots.push(new Slot([ContentType.Text, ContentType.InlineComponent]))
    }

    const stateController = useState<WordExplainComponentState>(state)

    const sub = stateController.onChange.subscribe(newState => {
      state = newState
    })
    const injector = useContext()
    const commander = injector.get(Commander)
    const i18n = injector.get(I18n)
    const dialog = injector.get(Dialog)
    const self = useSelf()

    onDestroy(() => {
      sub.unsubscribe()
    })

    onSlotRemove(ev => {
      ev.preventDefault()
    })

    const childI18n = i18n.getContext('components.wordExplainComponent.setter')

    function setting() {
      const form = new Form({
        title: childI18n.get('title'),
        confirmBtnText: childI18n.get('confirmBtnText'),
        cancelBtnText: childI18n.get('cancelBtnText'),
        items: [
          new FormTextField({
            name: 'width',
            value: state.width,
            placeholder: childI18n.get('widthInputPlaceholder'),
            label: childI18n.get('widthLabel')
          })
        ]
      })

      dialog.show(form.elementRef)

      const sub = form.onComplete.subscribe(data => {
        stateController.update(draft => {
          draft.width = data.width
        })
        dialog.hide()
        sub.unsubscribe()
      })
      sub.add(form.onCancel.subscribe(() => {
        dialog.hide()
        sub.unsubscribe()
      }))
    }

    onContextMenu(() => {
      return [{
        label: childI18n.get('title'),
        onClick() {
          setting()
        }
      }]
    })

    return {
      render(isOutputMode: boolean, slotRenderFn: SlotRender): VElement {
        return (
          <tb-word-explain>
            <div class="tb-word-explain-title-group" style={{width: state.width}}>
              {slotRenderFn(slots.get(0)!, () => {
                return <div class="tb-word-explain-title"/>
              })}
              {slotRenderFn(slots.get(1)!, () => {
                return <div class="tb-word-explain-subtitle"/>
              })}
            </div>
            {slotRenderFn(slots.get(2)!, () => {
              return <div class="tb-word-explain-detail"/>
            })}
            {
              !isOutputMode && <span class="tb-word-explain-close" onClick={() => {
                commander.removeComponent(self)
              }
              }/>
            }
          </tb-word-explain>
        )
      }
    }
  }
})

export const wordExplainComponentLoader: ComponentLoader = {
  component: wordExplainComponent,
  resources: {
    styles: [
      `
tb-word-explain {
  display: flex;
  margin-top: 1em;
  margin-bottom: 1em;
  padding: 10px 20px;
  background-color: #f8f8f9;
  border-radius: 10px;
}

.tb-word-explain-title-group {
  width: 140px;
  padding-right: 20px;
}
.tb-word-explain-title {
  margin:0;
  font-size: inherit;
}
.tb-word-explain-subtitle {
  margin: 0;
  font-weight: 300;
  font-size: 0.9em;
}
.tb-word-explain-detail {
  flex: 1;
  padding-left: 20px;
  border-left: 1px solid #ddd;
}
@media screen and (max-width: 767px) {
  tb-word-explain {
    display: block;
  }
  .tb-word-explain-title-group {
    width: auto !important;
    padding-right: 0;
    display: flex;
    align-items: baseline;
    padding-bottom: 0.5em;
    margin-bottom: 0.5em;
  }
  .tb-word-explain-subtitle {
    margin-left: 0.5em;
    font-weight: 300;
    font-size: 0.9em;
  }
  .tb-word-explain-detail {
    padding-left: 0;
    border-left: none;
  }
}
`
    ],
    editModeStyles: [
      `
tb-word-explain {
  position: relative;
}
tb-word-explain:hover .tb-word-explain-close {
  display: block;
}
.tb-word-explain-close {
  display: none;
  position: absolute;
  right: 10px;
  top: 0;
  font-size: 20px;
  line-height: 1;
  cursor: pointer;
}
.tb-word-explain-close:hover {
  transform: scale(1.2);
}
.tb-word-explain-close:before {
  content: "\u00d7";
}
`
    ]
  },
  match(element: Element): boolean {
    return element.nodeName.toLowerCase() === 'tb-word-explain'
  },

  read(element: HTMLElement, context: Injector, slotParser: SlotParser): ComponentInstance {
    const title = element.querySelector('.tb-word-explain-title') as HTMLElement
    const subtitle = element.querySelector('.tb-word-explain-subtitle') as HTMLElement
    const detail = element.querySelector('.tb-word-explain-detail') as HTMLElement

    const {Text, InlineComponent} = ContentType
    const titleSlot = new Slot([Text, InlineComponent])
    const subtitleSlot = new Slot([Text, InlineComponent])
    const detailSlot = new Slot([Text, InlineComponent])
    const width = (element.querySelector('.tb-word-explain-title-group') as HTMLElement).style.width

    slotParser(titleSlot, title)
    slotParser(subtitleSlot, subtitle)
    slotParser(detailSlot, detail)

    return wordExplainComponent.createInstance(context, {
      state: {
        width
      },
      slots: [
        titleSlot,
        subtitleSlot,
        detailSlot
      ]
    })
  }
}
